#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.1.1 (64-bit)
#
# Filename    : compile.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for compiling the simulation design source files
#
# Generated by Vivado on Mon Jan 25 20:05:56 CST 2021
# SW Build 2960000 on Wed Aug  5 22:57:21 MDT 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: compile.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xvlog --incr --relax -L axi_vip_v1_1_7 -L xilinx_vip -prj cb_sim_vlog.prj"
xvlog --incr --relax -L axi_vip_v1_1_7 -L xilinx_vip -prj cb_sim_vlog.prj 2>&1 | tee compile.log

echo "xvhdl --incr --relax -prj cb_sim_vhdl.prj"
xvhdl --incr --relax -prj cb_sim_vhdl.prj 2>&1 | tee -a compile.log

